version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - github_actions

  - package-ecosystem: pip
    directory: "/configs/docs"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python

  - package-ecosystem: pip
    directory: "/programs/python-programming/python-functional-programming/capstone"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python

  - package-ecosystem: pip
    directory: "/programs/python-programming/python-meta-programming/capstone"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python

  - package-ecosystem: pip
    directory: "/programs/python-programming/python-object-oriented-programming/capstone"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python

  - package-ecosystem: pip
    directory: "/programs/reproducible-research/deep-dive-dvc/capstone"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python

  - package-ecosystem: pip
    directory: "/programs/reproducible-research/deep-dive-snakemake/capstone"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python
