# workflow/modules/qc_module/Snakefile
from __future__ import annotations

import os

PYTHONPATH = os.path.join(workflow.basedir, "src")

rule qc:
    input:
        fastq="dummy.fastq.gz"
    output:
        json="qc.json",
        tsv="qc.tsv",
    log:
        "qc.log"
    benchmark:
        "qc.txt"
    conda:
        config["_env_python"]
    params:
        pythonpath=PYTHONPATH,
        benchdir=lambda wc: config["benchmarks_dir"],
    shell:
        r"""
        set -euo pipefail

        mkdir -p "$(dirname {output.json})" "$(dirname {log})" "{params.benchdir}"

        PYTHONPATH="{params.pythonpath}" \
        python3 -m capstone.qc_fastq \
            --in-fastq "{input.fastq}" \
            --out-json "{output.json}" \
            --out-tsv "{output.tsv}" 2> "{log}"
        """
